version: '3.8'

services:
  app:
    container_name: dealers-api-dev
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
      args:
        - NODE_ENV=development
    ports:
      - "${PORT:-3000}:3000"
      - "9229:9229" # Para debugging
    environment:
      - NODE_ENV=development
      - PORT=${PORT:-3000}
      - DATABASE_HOST=192.168.1.1
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=${DATABASE_USERNAME:-dealers}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-Dealer1234}
      - DATABASE_NAME=${DATABASE_NAME:-apidian}
      - JWT_SECRET=${JWT_SECRET:-dev_secret_key}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-15m}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET:-dev_refresh_secret_key}
      - JWT_REFRESH_EXPIRES_IN=${JWT_REFRESH_EXPIRES_IN:-7d}
    volumes:
      - ../../:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    networks:
      - dealers-network-dev
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s
networks:
  dealers-network-dev:
    driver: bridge
